#include<stdint.h>

#define WRITE_INT32(ADDR, DATA) *(volatile int32_t *)(ADDR) = (DATA)
#define WRITE_INT32_HIGH(ADDR, DATA) *(volatile int32_t *)(ADDR) = (DATA << 16)
#define READ_INT32(ADDR) *(volatile int32_t *)(ADDR)

#define MTIME 0xBFF8
#define MTIMECMP 0x4000
#define MTIMEWAIT 0x4008
#define START_TIME 0x10000

#define FREQ_GHZ(x) (int)(x * (1 << 13))
#define DEMOD_FREQ_GHZ(x) (int)(x * (1 << 15))
#define TIME_NS(x) (int)(x / 2)
#define PHASE_PI(x) (int)(x * (1 << 15))

#define SET_START_TIME(TIME) \
  WRITE_INT32(START_TIME, TIME);

#define SET_PULSE_FREQ(ID, FREQ) \
  WRITE_INT32_HIGH(PULSE_FREQ_ADDR(ID), FREQ);

#define SET_PULSE_ADDR(ID, ADDR) \
  WRITE_INT32_HIGH(PULSE_ADDR_ADDR(ID), ADDR);

#define SET_PULSE_AMP(ID, AMP) \
  WRITE_INT32_HIGH(PULSE_AMP_ADDR(ID), AMP);

#define SET_PULSE_DUR(ID, DUR) \
  WRITE_INT32_HIGH(PULSE_DUR_ADDR(ID), DUR);

#define SET_PULSE_PHASE(ID, PHASE) \
  WRITE_INT32_HIGH(PULSE_PHASE_ADDR(ID), PHASE);

#define SET_RD_DUR(ID, DUR) \
  WRITE_INT32_HIGH(RD_DUR_ADDR(ID), DUR);

#define GET_RD_RES(ID) \
  READ_INT32(RD_RES_ADDR(ID));

#define PULSE(ID, PHASE, AMP, ADDR, DUR) \
  SET_PULSE_PHASE(ID, PHASE); \
  SET_PULSE_AMP(ID, AMP); \
  SET_PULSE_ADDR(ID, ADDR); \
  SET_PULSE_DUR(ID, DUR); \

#define DEMOD_CARRIER(ID, FREQ, PHASE) \
  WRITE_INT32_HIGH(DEMOD_FREQ_ADDR(ID), FREQ); \
  WRITE_INT32_HIGH(DEMOD_PHASE_ADDR(ID), PHASE); \

#define PULSE_ID_BASE(ID) PULSE_BASE_ADDR + 0x100 * ID

#define PULSE_PHASE_ADDR(ID) PULSE_ID_BASE(ID) + PULSE_PHASE_OFFSET
#define PULSE_AMP_ADDR(ID) PULSE_ID_BASE(ID) + PULSE_AMP_OFFSET
#define PULSE_ADDR_ADDR(ID) PULSE_ID_BASE(ID) + PULSE_ADDR_OFFSET
#define PULSE_DUR_ADDR(ID) PULSE_ID_BASE(ID) + PULSE_DUR_OFFSET
#define PULSE_FREQ_ADDR(ID) PULSE_ID_BASE(ID) + PULSE_FREQ_OFFSET

#define DEMOD_ID_BASE(ID) DEMOD_BASE_ADDR + 0x100 * ID
#define DEMOD_FREQ_ADDR(ID) DEMOD_ID_BASE(ID) + DEMOD_FREQ_OFFSET
#define DEMOD_PHASE_ADDR(ID) DEMOD_ID_BASE(ID) + DEMOD_PHASE_OFFSET

#define RD_ID_BASE(ID) RD_BASE_ADDR + 0x100 * ID
#define RD_DUR_ADDR(ID) RD_ID_BASE(ID) + RD_DUR_OFFSET
#define RD_RES_ADDR(ID) RD_ID_BASE(ID) + RD_RES_OFFSET
#define RD_REAL_ADDR(ID) RD_ID_BASE(ID) + RD_REAL_OFFSET
#define RD_IMAG_ADDR(ID) RD_ID_BASE(ID) + RD_IMAG_OFFSET

#define PULSE_BASE_ADDR 0x20000
#define DEMOD_BASE_ADDR 0x30000
#define RD_BASE_ADDR 0x40000
#define PULSE_PHASE_OFFSET 0x10
#define PULSE_AMP_OFFSET 0x4
#define PULSE_ADDR_OFFSET 0x0
#define PULSE_DUR_OFFSET 0x8
#define PULSE_FREQ_OFFSET 0xc
#define DEMOD_FREQ_OFFSET 0x0
#define DEMOD_PHASE_OFFSET 0x4
#define RD_DUR_OFFSET 0x0
#define RD_RES_OFFSET 0x4
#define RD_REAL_OFFSET 0x8
#define RD_IMAG_OFFSET 0xc
